type Order {
    id: ID
    number: String!
    buyer: User @fetch(from: "buyerId" to:"id" anchor: true protocol: GRPC)
    goods: [Good!]
}

type Good {
    id: ID
    quantity: Int!
    order: Order!
    product: Product!
    merchant: Merchant!
}

type Product {
    id: ID
    name: String!
    price: Float!
}

type Merchant {
    id: ID
    name: String!
    organization: Organization @fetch(from: "organizationId" to: "id" anchor: true protocol: GRPC)
    customerServices: [User!]
    partners: [Organization!]
    director: User!
}