type Order {
    id: ID
    number: String!
    buyer: User @fetch(from: "buyerId" to:"id" anchor: true protocol: GRPC)
    goods: [Good!]
}

type Good {
    id: ID
    quantity: Int!
    order: Order!
    product: Product!
    merchant: Merchant!
}

type Product {
    id: ID
    name: String!
    price: Float!
}

type Merchant {
    id: ID
    name: String!
    organization: Organization @fetch(from: "organizationId" to: "id" anchor: true protocol: GRPC)
    customerServices: [User!] @fetch(from: "organizationId" to: "organizationId" protocol: GRPC)
    partners: [Organization!] @fetch(from: "id" with: {type: "MerchantPartners" from: "merchantId" to: "organizationId"} to: "id" anchor: true protocol: GRPC)
    director: User! @fetch(from: "id" with: {type: "MerchantDirector" from: "merchantId" to: "userId"} to: "id" anchor: true protocol: GRPC)
}