type User {
    id: ID
    login: String!
    password: String!
    name: String!
    age: Int
    disabled: Boolean
    sex: Sex
    userProfile: UserProfile @map(from: "id", to: "userId")
    organization: Organization
    roles: [Role!]
    mobileNumbers: [String!]
}

type UserProfile {
    id: ID
    userId: Int
    user: User
    email: String
    address: String
}

enum Sex {
    MAN
    FEMALE
}

type Role {
    id: ID
    name: String!
    roleType: [RoleType]!
    users: [User!]
}

enum RoleType {
    ADMIN
    USER
    ANONYMOUS
}

type Organization {
    id: ID
    parentId: Int
    name: String!
    above: Organization @map(from: "id", to: "parentId")
    users: [User!]
}